### ISSUE TITLE
all the text fields disabled after using jquery-mobile-iscrollview

### ISSUE THREAD

**Issue by mohsinraza** [watusi/jquery-mobile-iscrollview#18] opened 2012-06-05 11:00 UTC
firstly i was using the iscroll-4 then i browsed and find that jquery-mobile-iscrollview will be best option for mobile. after using this it is great but the issue is that all my text fields in the project are not working. I am too much worried and trying to figure out please help if you can. thanx for jquery-mobile-iscrollview it is great.

**Comment by padi** [comment] 2012-06-07 03:20
when using iscrollview on an iPad, I can't change focus into another input tag with touch. I always have to press 'next' in the keyboard.

also, i can't place the cursor in the middle of the textfield.

**Comment by jtara** [comment] 2012-06-25 18:17
Please try with 1.2 and report your results.

1.3 will be getting some attention to input specifically for iOS. The approach I will be taking will be to temporarily disable iScroll, restore the page structure, and hide headers and footers when the virtual keyboard is up. In other words, give the Forms Assistant exactly what it wants.

**Comment by jtara** [comment] 2012-06-26 17:28
I'm going to close this issue, since I cannot reproduce using version 1.2pre1. (Also can't reproduce with 1.1.)

If you are still experiencing this problem using 1.2pre1, please supply a complete example and give me browser details, and I will re-open.

Thanks.

**Closed as completed by jtara** 2012-06-26 17:28 UTC
Labels: cant_reproduce
